blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ KÃ©rdÃ©sed van? LÃ©pj velÃ¼nk kapcsolatba!
    url: https://github.com/<org>/<repo>/discussions
    about: Nem biztos vagy benne, melyik sablont hasznÃ¡ld? TegyÃ©l fel kÃ©rdÃ©st itt!

  - name: ğŸ”’ BiztonsÃ¡gi problÃ©ma
    url: https://github.com/<org>/.github/blob/main/SECURITY.md
    about: KÃ©rjÃ¼k, ne nyiss issue-t biztonsÃ¡gi problÃ©mÃ¡val kapcsolatban, Ã­rj inkÃ¡bb nekÃ¼nk privÃ¡t csatornÃ¡n.
